= Marakana Courseware Development Kit =

Marakana CDK is a set of tools, templates, documentation, and best practices for creating Marakana Beautiful Courseware.

== Requirements ==

CDK is based on http://www.methods.co.nz/asciidoc/[Asciidoc]. As such, it requires *Python* to be installed. Also, it currently uses http://www.gnu.org/software/src-highlite/[GNU Source-Highlight], which also should be installed.

Make sure CDK directory is in your path. In Bash, for example:

----
export PATH=$PATH:YOUR_PATH_TO/cdk
----

On OSX, you could just put the line above in your `~/.bash_profile`.

== Tools ==

`asc`::
The main tool is `asc`. It processes an AsciiDoc file and creates an output that adheres to Marakana Beautiful Courseware standards.


== Goodies ==

Templates::
Contains courseware templates, such as a module, an intro, a slide. It's work in progress!

Textmate::
Here, you will find the Textmate AsciiDoc bundle, as well as our extensions to Textmate to help with Beautiful Courseware development. The easiest way to add these bundles to your Textmate is the following:

----
cd ~/Library/Application\ Support/TextMate/Bundles
ln -s YOUR_PATH_TO/cdk/textmate/Marakana.tmbundle .
ln -s YOUR_PATH_TO/cdk/textmate/AsciiDoc.tmbundle .
----

Style Guide::
This is the original style guide for developing courseware. Needs an update.
