= Marakana Courseware Development Kit =

== Overview of CDK ==

Marakana CDK is a set of tools, templates, documentation, and best practices for creating Beautiful Courseware.

CDK is based on http://www.methods.co.nz/asciidoc/[Asciidoc] as the markup for authoring. New to AsciiDoc? Check out this http://powerman.name/doc/asciidoc[cheatsheet].

== Portable, Modular, Consistent Authoring ==

.CDK Promise
image::docs/CDK.svg[]

// TODO: Add the links to these
An example of what is possible to with CDK is this conference talk that is later on also published as an article fitting the stream.

== What's Included in the Kit ==

Toolchain::
CDK comes with the *AsciiDoc*. We also included two AsciiDoc backends: Deck.js and Slidy2. Deck.js backend produces slide-like view of your content and we've customized it to work for learning purposes.

Templates::
Additionally, CDK includes courseware *templates* for a course, module, and slide. You can find these in `[CDK]/templates/` folder. Specifically look at `Course.asc`, `Module.asc`, and `Slide.asc`.

Samples::
We've also included *sample courses* to help you see how to develop courseware using CDK. You can find them in `[CDK]/samples/` folder. The output is the HTML file in each source folder.

Best Practices::
CDK is an attempt to bottle up the *best practices* for creating course materials, based on our experience at Marakana. We call these practices _Beautiful Courseware_

== What CDK Is For ==

Rapidly Create::
CDK is designed to allow you to *rapidly create* great looking course material. It uses a simple markup text based on AsciiDoc, and some basic rules about what makes up a courseware. 

Modularize Content::
With CDK templates for what makes up a course and a module, your content will be well-modularized so you can easily mashup various modules into custom classes for specific needs.

Make it Beautiful in Any Form::
CDK takes care of making your content look great. It comes with various templates, and you can easily create your own. As such, the content itself should be as much look&feel-free as possible. In other words, focus on content, not its presentation and CDK will do its best to make it look beautiful.



// Beautiful Courseware
include::docs/Beautiful_Courseware.asc[]

// Setup Instructions
include::docs/Setup.asc[]

== Feature Requests ==

* Absolute tool bar that contains the following:
** Bread crumbs, clickable
** Help
** Slide number

* A tool to publish a course or a module directly to the cloud, such as S3, with a link to it.

* SCORM export so it can produce content for other LMSs

* Help
* About Marakana
* About other instructors who teach this course?
* About the author
* Legal


* Advancing to the next slide (or going back) does not move the viewport to the top of the page.
* Using consecutive note/tip/warning images makes the first image appear disproportionately small.
* We should use the up arrow to move back to the beginning of the module?
* Position the module titles (H2s) in the middle of the page


// Legal
include::Legal-Disclaimer.asc[]