= Marakana Courseware Development Kit =

Marakana CDK is a set of tools, templates, documentation, and best practices for creating Marakana Beautiful Courseware.

It is based on http://www.methods.co.nz/asciidoc/[Asciidoc] as the authoring tool right now, modified Deck.js as presentation template, and a lot of glue to hold it all together.

== Requirements ==

You need Python. If running on a platform other than OSX, you also need http://www.gnu.org/software/src-highlite/[GNU Source-Highlight].

Make sure CDK directory is in your path. In Bash, for example:

----
export PATH=$PATH:YOUR_PATH_TO/cdk
----

On OSX, you could just put the line above in your `~/.bash_profile`.

== Tools ==

`asc`::
The main tool is `asc`. It processes an AsciiDoc file and creates an output that adheres to Marakana Beautiful Courseware standards.

`post`::
Creates Marakana Stream-ready posts from a module.


== Goodies ==

Templates::
Contains courseware templates, such as a module, an intro, a slide. It's work in progress!

Textmate::
Here, you will find the Textmate AsciiDoc bundle, as well as our extensions to Textmate to help with Beautiful Courseware development. The easiest way to add these bundles to your Textmate is the following:
+
----
cd "~/Library/Application\ Support/TextMate/Bundles"; 
ln -s YOUR_PATH_TO/cdk/textmate/Marakana.tmbundle . ; 
ln -s YOUR_PATH_TO/cdk/textmate/AsciiDoc.tmbundle . ;
----

Textmate2::
For Textmat2, you need to link to a https://github.com/zuckschwerdt/asciidoc.tmbundle[different bundle], already included in CDK:
+
----
cd "~/Library/Application\ Support/Avian/Bundles"; 
ln -s YOUR_PATH_TO/cdk/textmate2/asciidoc.tmbundle . ;
----
+
Also, you have to add `PATH` variable to point to your CDK directory by going to TextMate->Preferences->Variables.
+
If you don't like Textmate2 opening the preview in split pane, and prefer a new window, run the following in your Terminal:
+
----
defaults write com.macromates.TextMate.preview htmlOutputPlacement window
----


Style Guide::
This is the original style guide for developing courseware. Needs an update.


== Feature Requests ==

* A tool to publish a course or a module directly to the cloud, such as S3, with a link to it.

* Be able to have a slide with no title (empty H2 is fine).

* Support for breadcrumbs in slides.